### ISSUE TITLE
libsgx: Reproducible libraries and open source

### ISSUE THREAD

**Issue by zaolin** [01org/linux-sgx#1]
Hi,

I would recommend to make the libsgx stuff open source and provide prebuilt reproducible libraries
in order to verify it content. I would also help people to investigate bugs and lead to transparency.

For more information:
https://wiki.debian.org/ReproducibleBuilds

**Comment by zaolin** [comment]
Some more documentation about tools and process.
https://reproducible-builds.org/docs/

**Comment by zhaohuidu** [comment]
Thanks for the useful information. Is only Debian supported for the reproduciblebuilds currently?

**Comment by lynxis** [comment]
reproducible builds is a concept which improves security. it validates the source-code to the binary, but the source must be available. debian project did a great effort and pushed the topic accross distributions.

see https://media.ccc.de/v/996-reproducible-builds-everywhere-and-beyond for a recent talk about or
see https://reproducible-builds.org/

**Comment by zaolin** [comment]
@zhaohuidu So are there any plans to provide the libraries source code ?

**Comment by andyzyb** [comment]
There is no plan to support ReproducibleBuilds in short term as it is still in development stage.

**Comment by Hans-Giebenrath** [comment]
I have not found any explicit statement, whether the sgx sdk nowadays supports reproducible builds. The closest thing to an inofficial statement is this form post: https://software.intel.com/en-us/forums/intel-software-guard-extensions-intel-sgx/topic/746362, but something more official and easily visible (and google'able) would be nice. Or is the last comment ("There is no plan to support ReproducibleBuilds") still valid?

**Comment by andyzyb** [comment]
Reproduciblebuilds is another project originated from Debian but Debian is currently not in the supported OS list.   So there is no plan to support ReproducibleBuilds now.   

To reproduce the build of SDK,  if you use the same build environment as stated in README, it likely will result in the same binaries. But this cannot be guaranteed since small updates in the compiler or other libraries may generate different results.
