### ISSUE TITLE
IPP Crypto Libs

### ISSUE THREAD

**Issue by adilahmad17** [01org/linux-sgx#103]
Hi, 

Can you please provide some example script illustrating how to use the IPP libraries within an SGX Enclave? The examples provided at the IPP link don't work with SGX because of BigNumber issues. 

More specifically, I am looking to run ippsRSA_encrypt() and ippsRSA_decrypt().

Thanks!

**Comment by lzha101** [comment]
The IPP functionalities are packaged into `libsgx_tcrypto.a` and the IPP header files could be found in `external/ippcp_internal` or `external/crypto_px`.  To use the IPP functions in an enclave,  you can include the IPP header files in your enclave source files, write your code to use the IPP functions directly and link the `libsgx_tcrypto.a` in the enclave build script.   You may need to use the corresponding IPP header files to align with what are used in `libsgx_tcrypto.a` compilation.  For example, if you build SGX SDK with precompiled optimized libraries, you'd better to use the header files from `external/ippcp_internal`; and if you build SGX SDK with non-optimized source code implementation (by `make USE_OPT_LIBS=0` to build the repo), please use IPP header files from `external/crypto_px`.

The link includes an example of using RSA Primitive Functions: https://software.intel.com/en-us/node/503498.  Hope it helps you.

**Comment by lzha101** [comment]
For the BigNumber issue, it is not standard class for IPP. You can find the reference implementation from: https://software.intel.com/en-us/ipp-crypto-reference-2018-beta-bignumber-class

**Comment by adilahmad17** [comment]
Ah, alright. Thank you so much for all this information!
