### ISSUE TITLE
error unsealing data in Java but working in C++

### ISSUE THREAD

**Issue by jresende** [01org/linux-sgx#108]
I'm using in Ubuntu intel sgx to seal and unseal data.

I have both implementation in C and Java.

The example is simple:

Seal the data
Restart the program
Unseal the data
This works fine in C++ but when I'm using Java the program gives segmentation fault.

I guess that is related with the Makefile options that I need to setup the library to use in Java, that are the following:
```

App_SO_Name := libSGXEnclave.so

$(App_SO_Name): App/Enclave_u.o $(App_Cpp_Objects)
	@echo "LINK =>  $@"
	@$(CXX) $^ $(App_Link_Flags) -shared -o $@
```
The remaining part of the Makefile and other things related with the code can be found in https://github.com/digawp/hello-enclave/

I'm available to give further information regarding this issue.

**Comment by andyzyb** [comment]
Are you calling Enclave code through JNI?  C/C++ is the only language supported to develop an Enclave. do you have any clue where the program is crashed?

**Comment by jresende** [comment]
The following example describes the process of unsealing in both examples. Yes I'm using Jni. I comment the place where the program crashes.


Java / JNI example
```
JNIEXPORT jstring JNICALL Java_Joao_unseal(
  JNIEnv *env, jobject obj, jstring javaString) {
	if (initialize_enclave(&global_eid, "enclave.token", "enclave.signed.so") < 0) {
		std::cout << "Fail to initialize enclave." << std::endl;
	        return NULL;
	}
 sgx_status_t status;
    sgx_status_t ecall_status;

  const char * teste;

	 size_t sealed_size = sizeof(sgx_sealed_data_t) + sizeof(teste);
    uint8_t* sealed_data = (uint8_t*) malloc(sealed_size);

	FILE *fp;
 	fp = fopen("simple.zod", "a+");
 	int numRead = fread(sealed_data,sealed_size, 1, fp );
 	if (numRead == 0) {
        	return NULL;
        }
	fclose(fp);
   
    status = unseal(global_eid, &ecall_status,
            (sgx_sealed_data_t*)sealed_data, sealed_size,
            (uint8_t*)&teste,  sizeof(teste));

    if (!is_ecall_successful(status, "Unsealing failed :(", ecall_status)) {
        return NULL;
    }

    std::cout << "Seal round trip success! Receive back final -> " << teste << "end"<< std::endl;  // the error is at this point
    return (env)->NewStringUTF("teste");
}
```
The error is in the print function:
`std::cout << "Seal round trip success! Receive back final -> " << teste << "end"<< std::endl
`
C++ code that I use is this:

```

int  unseal(){
	if (initialize_enclave(&global_eid, "enclave.token", "enclave.signed.so") < 0) {
		std::cout << "Fail to initialize enclave." << std::endl;
	        return NULL;
	}
 sgx_status_t status;
    sgx_status_t ecall_status;

  const char * teste;

	 size_t sealed_size = sizeof(sgx_sealed_data_t) + sizeof(teste);
    uint8_t* sealed_data = (uint8_t*) malloc(sealed_size);

	FILE *fp;
 	fp = fopen("simple.zod", "a+");
 	int numRead = fread(sealed_data,sealed_size, 1, fp );
 	if (numRead == 0) {
        	return NULL;
        }
	fclose(fp);

    status = unseal(global_eid, &ecall_status,
            (sgx_sealed_data_t*)sealed_data, sealed_size,
            (uint8_t*)&teste,  sizeof(teste));


    if (!is_ecall_successful(status, "Unsealing failed :(", ecall_status)) {
        return NULL;
    }
 
    std::cout << "Seal round trip success! Receive back final -> " << teste << "end"<< std::endl;


return 1;
}
```

Note that I can unseal if I do not stop the program. The problem is when I start the program again.
I can give information regarding the seal process or make the project fully available.

**Comment by haitaohuang** [comment]
Couple things you might want to check:
1) You passed &teste (which would be "const char**", but casted to uint_8*) into ecall as out buffer to receive unsealed data.. 
2) I don't see anywhere you actually allocating the buffer pointed to by teste

**Comment by jresende** [comment]
I already allocate the teste variable. But regarding the point 1, what is the problem? I used the same code in the C and is working as expected

**Comment by llly** [comment]
`cout << teste`
 crashes your app.  You need to change it it 
`cout<<(int)teste`
