### ISSUE TITLE
Ubuntu 16 LTS works too

### ISSUE THREAD

**Issue by mikehearn** [01org/linux-sgx#11]
I accidentally ended up installing the latest Ubuntu and decided to proceed anyway. The SGX example apps all run in hardware mode just fine, at least on my HP machine. You could update the README to reflect that.

**Comment by OrionBytes** [comment]
Linux Mint 18 Sarah too

**Comment by zhaohuidu** [comment]
Thanks for the information.
The code may also work on other Linux platform. But we could not guarantee it.

**Comment by andyzyb** [comment]
Supporting Ubuntu 16.04 is experimental.
