### ISSUE TITLE
error while building SampleEnclave program

### ISSUE THREAD

**Issue by soso19932603** [01org/linux-sgx#116]
Hello,
when i am trying to build SampleEnclave program, using make command i get this error:
 
make: *** No rule to make target '/opt/intel/sgxsdk/bin/x64/sgx_edger8r', needed by 'App/Enclave_u.c'.

What does it mean?

**Comment by soso19932603** [comment]
I have found solution, when installing sgx sdk with the following command 
 sudo ./sgx_linux_x64_sdk_${version}.bin . It suggest two choice : 
  1- install sdk in current directory.  or   
  2- Another one. 
So i have chosen the second suggestion : (/opt/intel).

**Comment by johnvenn** [comment]
notice there was a message on the end of sgxsdk installation -- run this command "source your_selected_sdk_installation_path/environment"

**Comment by lzha101** [comment]
Just as @johnvenn mentioned, you need to source the environment before you build the SampleEnclave.

**Comment by soso19932603** [comment]
Yes it also works, thanks for your responses

**Comment by lzha101** [comment]
If no other errors, can we close this issue? @soso19932603

**Comment by soso19932603** [comment]
No other errors, we can close it, thanks !

**Comment by BSDinis** [comment]
I sourced the environment and it still gives me this exact error message

**Comment by simplespy** [comment]
I have the same problem even after setting the source

**Comment by andyzyb** [comment]
It may be caused by sample code Makefile.  Is that sample code you are using the latest one from github?

**Comment by Jiax-cn** [comment]
> 

Thank u!  I reinstall the SDK to `/opt/intel`, problem solved.
