### ISSUE TITLE
aesmd fails to start after reboot

### ISSUE THREAD

**Issue by rodolfoams** [01org/linux-sgx#117]
There seems to be a problem with AESM when the system reboots. I can reproduce this problem both on VMs and on physical machines. Here is a full log:

[before reboot]
ubuntu@sc-kvm-sgx1:~/sgx-install$ sudo service aesmd status
● aesmd.service - Intel(R) Architectural Enclave Service Manager
   Loaded: loaded (/lib/systemd/system/aesmd.service; enabled; vendor preset: enabled)
   Active: active (running) since Ter 2017-06-20 06:08:32 BRT; 10s ago
  Process: 23333 ExecStart=/opt/intel/sgxpsw/aesm/aesm_service (code=exited, status=0/SUCCESS)
 Main PID: 23335 (aesm_service)
    Tasks: 4
   Memory: 2.3M
      CPU: 13ms
   CGroup: /system.slice/aesmd.service
           └─23335 /opt/intel/sgxpsw/aesm/aesm_service

Jun 20 06:08:32 sc-kvm-sgx1 systemd[1]: Starting Intel(R) Architectural Enclave Service Manager...
Jun 20 06:08:32 sc-kvm-sgx1 systemd[1]: Started Intel(R) Architectural Enclave Service Manager.
Jun 20 06:08:32 sc-kvm-sgx1 aesm_service[23335]: [ADMIN]Platform Services initializing
Jun 20 06:08:32 sc-kvm-sgx1 aesm_service[23335]: [ADMIN]Platform Services initialization failed due to DAL error
Jun 20 06:08:32 sc-kvm-sgx1 aesm_service[23335]: The server sock is 0x8eb560

[after reboot]
ubuntu@sc-kvm-sgx1:~$ sudo service aesmd status
● aesmd.service - Intel(R) Architectural Enclave Service Manager
   Loaded: loaded (/lib/systemd/system/aesmd.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Ter 2017-06-20 06:10:33 BRT; 10min ago
  Process: 936 ExecStart=/opt/intel/sgxpsw/aesm/aesm_service (code=exited, status=0/SUCCESS)
 Main PID: 1050 (code=exited, status=0/SUCCESS)

Jun 20 05:50:29 sc-kvm-sgx1 systemd[1]: Starting Intel(R) Architectural Enclave Service Manager...
Jun 20 05:50:30 sc-kvm-sgx1 systemd[1]: Started Intel(R) Architectural Enclave Service Manager.
Jun 20 05:50:30 sc-kvm-sgx1 aesm_service[1050]: [ADMIN]Platform Services initializing
Jun 20 05:50:30 sc-kvm-sgx1 aesm_service[1050]: [ADMIN]Platform Services initialization failed due to DAL error
Jun 20 05:50:30 sc-kvm-sgx1 aesm_service[1050]: The server sock is 0x10042f0
Jun 20 05:50:30 sc-kvm-sgx1 aesm_service[1050]: Failed to create socket

**Comment by andersgjerdrum** [comment]
I can confirm, seeing the same behaviour when rebooting. 
"Platform Services initialization failed due to DAL error"
Possibly a recently introduced breaking change.

**Comment by llly** [comment]
It's a known bug of aesm_service. You can uninstall psw installer and install it again to workaround it. We will fix it in next major release.

**Comment by kaimast** [comment]
Make sure you create the folder /var/run/aesmd. Then chown aesmd /var/run/aesmd

**Comment by llly** [comment]
fixed in  commit 0fb9f47

**Comment by rodolfoams** [comment]
I can confirm that this has been solved. I'm closing the issue.

**Comment by kaimast** [comment]
I still have to manually create /var/run/aesmd. Should i file another bug for this?

**Comment by kaimast** [comment]
Nevermind. Rebulit the PSW and now it has been resolved. Thanks so much for fixing this!

**Comment by rodolfoams** [comment]
aesmd fails to start after reboot again. The cause of the problem seems to have changed though.

rodolfomarinho@triunfo-pc-18:~$ sudo service aesmd status
● aesmd.service - Intel(R) Architectural Enclave Service Manager
   Loaded: loaded (/lib/systemd/system/aesmd.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Seg 2017-07-31 15:06:36 BRT; 8s ago
  Process: 3145 ExecStart=/opt/intel/sgxpsw/aesm/aesm_service (code=exited, status=0/SUCCESS)
  Process: 3142 ExecStartPre=/bin/chmod 0755 /var/run/aesmd/ (code=exited, status=0/SUCCESS)
  Process: 3138 ExecStartPre=/bin/chown -R aesmd:aesmd /var/run/aesmd/ (code=exited, status=0/SUCCESS)
  Process: 3136 ExecStartPre=/bin/mkdir -p /var/run/aesmd/ (code=exited, status=0/SUCCESS)
 Main PID: 3146 (code=exited, status=1/FAILURE)

Jul 31 15:06:36 triunfo-pc-18 systemd[1]: aesmd.service: Unit entered failed state.
Jul 31 15:06:36 triunfo-pc-18 systemd[1]: aesmd.service: Failed with result 'exit-code'.

**Comment by kaimast** [comment]
Are you sure the isgx driver is running?

**Comment by rodolfoams** [comment]
Thank you for pointing that out. That was my problem.
