### ISSUE TITLE
SIGSEGV due to malloc failure with SGX_MODE=SIM and HeapMaxSize=0

### ISSUE THREAD

**Issue by sean-jc** [01org/linux-sgx#12]
The simulation flow for EREPORT includes a call to `sgx_rijndael128_cmac_msg`, which uses `malloc` to allocate the buffer for the temporary CMAC state.  This causes SGX applications to crash when compiled with HeapMaxSize=0 and SGX_MODE=SIM.  The same application runs clean with HeapMaxSize=0 and SGX_MODE=HW as there are no heap allocations in the application itself.  Running with HeapMaxSize=0 may not be recommended/common, but the simulator should not crash on an application that runs clean on hardware.

Replacing `malloc` with `alloca` in `sgx_rijndael128_cmac_msg` seems like a viable solution, as the temp buffer is fully contained within the function and is relatively small (less than 1k bytes).  This approach allows the application to run cleanly in the simulator with HeapMaxSize=0 and StackMaxSize=0x4000.

Code to reproduce the issue can be found at this [commit](https://github.com/sean-jc/STREAM/commit/19a8467a4d0e16b033d24ee6aaea8a23dac29e97).

```
Program received signal SIGSEGV, Segmentation fault.
0x00007fffee8e872b in sys_alloc (m=0x7ffff3304280 <_gm_>, nb=688) at stdlib/malloc.c:4299
4299      MALLOC_FAILURE_ACTION;
(gdb) bt
#0  0x00007fffee8e872b in sys_alloc (m=0x7ffff3304280 <_gm_>, nb=688) at stdlib/malloc.c:4299
#1  0x00007fffee8eba9e in malloc (bytes=671) at stdlib/malloc.c:4728
#2  0x00007fffee8fb392 in sgx_rijndael128_cmac_msg (p_key=0x7fffee8ff3b0 <BASE_REPORT_KEY>, p_src=0x7ffff330a148 "\003", src_len=120, p_mac=0x7ffff330a130) at sgx_cmac128.cpp:62
#3  0x00007fffee8e410f in derive_key (dd=0x7ffff330a140, okey=0x7ffff330a130 "") at /home/sean/go/src/github.com/01org/linux-sgx/sdk/simulation/trtssim/linux/../../tinst/deriv.cpp:86
#4  0x00007fffee8e3e50 in _EREPORT (ti=0x7fffee8ff000 <SYNTHETIC_STATE>, rd=0x7fffee8ff000 <SYNTHETIC_STATE>, report=0x7ffff330aa00) at /home/sean/go/src/github.com/01org/linux-sgx/sdk/simulation/trtssim/linux/../../tinst/t_instructions.cpp:273
#5  0x00007fffee8e404c in _SE3 (xax=0, xbx=140737195798528, xcx=140737195798528, xdx=140737273440768, xsi=140737195798528, xdi=140737195798528) at /home/sean/go/src/github.com/01org/linux-sgx/sdk/simulation/trtssim/linux/../../tinst/t_instructions.cpp:343
#6  0x00007fffee8e4489 in do_ereport () at /home/sean/go/src/github.com/01org/linux-sgx/sdk/trts/linux/trts_pic.S:410
#7  0x00007ffff330aa00 in ?? ()
#8  0x00007fffee8ff000 in ?? ()
#9  0x00007ffff330c000 in ?? ()
#10 0x00007fffee8e2de0 in get_xfeature_state () at /home/sean/go/src/github.com/01org/linux-sgx/sdk/trts/trts_xsave.cpp:66
#11 0x00007fffee8e17c1 in init_enclave (enclave_base=0x7fffee8e0000, ms=0x7fffffffb990) at /home/sean/go/src/github.com/01org/linux-sgx/sdk/trts/init_enclave.cpp:101
#12 0x00007fffee8e186b in do_init_enclave (ms=0x7fffffffb990) at /home/sean/go/src/github.com/01org/linux-sgx/sdk/trts/init_enclave.cpp:129
#13 0x00007fffee8e1d13 in enter_enclave (index=-1, ms=0x7fffffffb990, tcs=0x7ffff330c000, cssa=0) at /home/sean/go/src/github.com/01org/linux-sgx/sdk/trts/trts.cpp:307
#14 0x00007fffee8e42a1 in enclave_entry () at /home/sean/go/src/github.com/01org/linux-sgx/sdk/trts/linux/trts_pic.S:136
#15 0x00007ffff7bb2b2d in __morestack () at enter_enclave.S:56
#16 0x00007ffff7bab9f0 in do_ecall (fn=-1, ocall_table=0x0, ms=0x7fffffffb990, trust_thread=0x616830) at /home/sean/go/src/github.com/01org/linux-sgx/psw/urts/linux/sig_handler.cpp:244
#17 0x00007ffff7b9f848 in CEnclave::ecall (this=0x616690, proc=-1, ocall_table=0x0, ms=0x7fffffffb990) at /home/sean/go/src/github.com/01org/linux-sgx/psw/urts/enclave.cpp:165
#18 0x00007ffff7bb223b in EnclaveCreatorSim::initialize (this=0x615030, enclave_id=91933774970882) at ../enclave_creator_sim.cpp:223
#19 0x00007ffff7ba9ba5 in __create_enclave (parser=..., base_addr=0x7ffff7f99000 "\177ELF\002\001\001", metadata=0x7ffff7fbd1c9, file=..., debug=true, lc=0x615220, prd_css_file=0x0, enclave_id=0x7fffffffdf28, misc_attr=0x0)
    at /home/sean/go/src/github.com/01org/linux-sgx/psw/urts/urts_com.h:247
#20 0x00007ffff7ba9fc9 in _create_enclave (debug=true, pfile=3, file=..., prd_css_file=0x0, launch=0x7fffffffdf30, launch_updated=0x7fffffffdf24, enclave_id=0x7fffffffdf28, misc_attr=0x0) at /home/sean/go/src/github.com/01org/linux-sgx/psw/urts/urts_com.h:333
#21 0x00007ffff7baa2ce in sgx_create_enclave (file_name=0x401272 "stream_enclave.signed.so", debug=1, launch_token=0x7fffffffdf30, launch_token_updated=0x7fffffffdf24, enclave_id=0x7fffffffdf28, misc_attr=0x0)
    at /home/sean/go/src/github.com/01org/linux-sgx/psw/urts/linux/urts.cpp:60
#22 0x00000000004007d6 in main ()
```

**Comment by zhaohuidu** [comment]
Replace malloc with alloca doesn't solve the problem since stack size could be not enough too.
Here the simulation mode of the code works different with the hardware mode because your code in hardware mode may not use any heap memory while in simulation mode, the simulation of instruction _EREPORT will consume some heap.
Replacing malloc with alloca will require different size requirement of stack size in simulation mode and hardware mode too.
And we should not expect the simulation mode always work same as hardware mode.

**Comment by sean-jc** [comment]
> Replace malloc with alloca doesn't solve the problem since stack size could be not enough too.
> ...
> Replacing malloc with alloca will require different size requirement of stack size in simulation mode and hardware mode too.

Using alloca in this situation does not affect the minimum stack size required by the SDK in simulation mode[1].  I agree that this isn't foolproof against future changes, but it does work in today's code base and will continue to work unless either (a) the minimum stack size is reduced to 0x1000 bytes by optimizing stack usage in the rest of the _EREPORT code, (b) the AES-CMAC size increases 6x or (c) the simulator's _EREPORT flow consumes an additional ~4000 bytes of stack space[2] .  The same cannot be same for malloc, as it is guaranteed to fail because it's literally the only heap allocation in a mandatory code flow.

> And we should not expect the simulation mode always work same as hardware mode.

I don't disagree, and if there were a minimum heap size for the SDK in hardware mode I probably wouldn't care as much, but I think the zero-to-nonzero transition is a special case.  In general I think that requiring a minimum stack size is a better approach than requiring a minimum heap size (for basic behavior).  Anything beyond the most trivial application will need more than a 0x1000 byte stack, i.e. the SDK simulator's minimum stack size is unlikely to factor into the application's overall minimum stack size.  On the other hand, I think it's reasonable for an application to deliberately avoid heap allocations, e.g. for performance or security.

[1] The simulator's _EREPORT already necessitates increasing the application's StackMaxSize from 0x1000 to 0x2000 bytes due to other non-trivial structures being placed on the stack.

[2] The RSP offset when entering sgx_rijndael128_cmac_msg in simulation mode on my system is 0xfc0, i.e. there is essentially an entire 4k page of available stack.  The AES-CMAC size is 671 bytes.

**Comment by sean-jc** [comment]
As of the 1.6 build fails due to `alloca` change as the AESM service is now referencing sgx_rijndael128_cmac_msg and g++ doesn't link alloca by default.

Digging into the code it looks like the only call to EREPORT that is mandatory (occurs for all enclaves in the default flow) is in get_xfeature_state() via init_enclave->().  The ultimate goal of the call is to get the XFRM value from SECS.ATTRIBUTES.  It seems like it should be possible to define/know the SECS XFRM value when the enclave is being built, which would avoid EREPORT altogether.

**Comment by yuyuany** [comment]
SECS.ATTRIBUTES is generated at run time, it depends on user's input and the platform capability. So the enclave should call EREPORT to read SECS.ATTRIBUTES. It cannot be avoided.

**Comment by sean-jc** [comment]
Submitted PR #16.  XCR0 is loaded directly from SECS.ATTRIBUTES.XFRM, I can't think of any reason why the XFRM value from SECS can't be used as the runtime XCR0 value.

**Comment by yuyuany** [comment]
The reason of getting SECS.ATTRIBUTES within the enclave is to know which features are used within the enclave. And when exiting the enclave, we need to clean all related registers to avoid secret leak. We should note that uRTS is not trusted. We cannot trust the parameters passing from uRTS, especially for XFRM. If the parameter is hacked, and some registers are ignored to be cleared, maybe some sensitive data is leaked. 
The XFRM value from SECS is just XCR0 value within the enclave. But unfortunately XCR0 cannot be safely read within the enclave, because xgetbv throws #UD if xsave is not supported, and the check of xsave support needs CPUID instruction, which is illegal within enclave. So we need EREPORT to read the XFRM value.

**Comment by sean-jc** [comment]
Ah, that makes sense.

Are there plans to expose XFRM/XFRM_MASK to the user via the EnclaveConfiguration XML?  If so then it would be fairly easy to optimize out the EREPORT when all XFRM are explicitly defined, e.g. the user's values for XFRM/XFRM_MASK could be stored in g_global_data.  EREPORT isn't the most expensive instruction, but it's slow enough to measurable, and it seems like there will be applications that want to force features on/off, .e.g AVX or MPX.

**Comment by yuyuany** [comment]
Yes, we will expose the bits that enclave supports to the user via the EnclaveConfiguration XML. But as I stated before, SECS.ATTRIBUTES is determined by both user's input and the platform capability. 

Take AVX-512 as an example, which is not supported and always disabled in the latest release. If one day we support it within enclave, we may expose an interface for user to choose whether to use it or not. 
- If user force AVX-512 enabled within the enclave, but the platform doesn't support this feature, loading enclave fails. 
- If user does not force AVX-512 enabled or disabled, which XFRM_MASK.AVX512 = 0, then SECS.ATTRIBUTES.XFRM.AVX512 = XCR0.AVX512. In this case, SECS.ATTRIBTES cannot be determined only by XFRM/XFRM_MASK that stored in g_global_data. Some optimized libraries like IPP may generate two sets of instructions for a function, one with AVX512 instructions, and the other not. The code will choose one of them to execute at the run time, based on the parameter cpu_feature passed from uRTS during the enclave initialization. Note that this parameter is also not trusted, but hacking it only affects the features used within the enclave, no security issue can be introduced. No matter AVX-512 instructions are used or not, the AVX-512 related registers will be cleared before exiting the enclave as long as SECS.ATTRIBUTES.XFRM.AVX512 = 1.

**Comment by sean-jc** [comment]
>Yes, we will expose the bits that enclave supports to the user via the EnclaveConfiguration XML. But as I stated before, SECS.ATTRIBUTES is determined by both user's input and the platform capability.

Right, but there will be scenarios where the outcome is fully defined.  For example, if `XFRM.AVX` is forced to `1`, then either the enclave will fail to load or `SECS.ATTRIBUTES.AVX==1`, in which case the tRTS can skip EREPORT during init since it is guaranteed to run if and only if XSAVE is supported.  The safe approach would be to only do the optimized flow if all bits are fixed.  Example code below.

```c
uint64_t get_xfeature_state()
{
    // The global data contains the XFRM and XFRM_MASK values defined by the
    // user.  Bits that are not fixed, e.g. mask bit is not set, are evaluated
    // at runtime by the uRTS loader and set if possible, e.g. XCR0.AVX is set
    // if the OS has enabled CR4.OSXSAVE.  For the tRTS side, if any consumed
    // bit is floating, then it must query the XCR0 value after the enclave is
    // loaded, which unfortunately means executing EREPORT as XGETBV will #UD
    // in the enclave.  If all bits are fixed then we can skip EREPORT.  Note
    // that we don't need to worry about ignoring reserved or legacy bits, the
    // signing tool is responsible for sanitizing them.
    uint64_t xfrm = g_global_data.xfrm;
    if (~g_global_data.xfrm_mask) {
        // target_info and report_data are useless
        // we only need to make sure their alignment and within enclave
        // so set the pointers to SYNTHETIC_STATE
        sgx_target_info_t *target_info = (sgx_target_info_t *)SYNTHETIC_STATE;
        sgx_report_data_t *report_data = (sgx_report_data_t *)SYNTHETIC_STATE;
        uint8_t buffer[sizeof(sgx_report_t) + REPORT_ALIGN_SIZE -1] = {0};
        sgx_report_t *report = (sgx_report_t *)ROUND_TO((size_t)buffer, REPORT_ALIGN_SIZE);

        for (int i = 0; i < 1000000; i++)
            do_ereport(target_info, report_data, report);

        xfrm = report->body.attributes.xfrm;

        // no secrets in target_info, report_data, and report. no need to clear them before return
        // tlibc functions cannot be used before calling init_optimized_libs().
    }

    g_xsave_enabled = XFEATURE_ENABLED_AVX(xfrm) ? 1 : 0;

    return xfrm;
}
```

**Comment by andyzyb** [comment]
Using EREPORT is a much simpler implementation which we don't need to care about the difference of user's settings.

**Comment by yuyuany** [comment]
We cannot guarantee that g_global_data.xfrm is exactly the same as SECS.attributes.xfrm. g_global_data is measured, but SECS.attributes is not measured.

**Comment by andyzyb** [comment]
Simulation mode is likely different from real hardware mode and heap size is unlikely zero for majority of the applications.   Close it as it has relatively low value to support zero heap size in simulation mode.
