### ISSUE TITLE
sgx-gdb hangs at launch

### ISSUE THREAD

**Issue by Moschn** [01org/linux-sgx#121]
One of the recent commits to the sdk broke the provided gdb debugger. `sgx-gdb` hangs at launch on my machine (Ubuntu 16.04).

The debugger still works on the last commit before 1.9 (199911ebaf60d068e4641331a06e71462ba8d324)

**Comment by hyjiang** [comment]
I cannot reproduce this issue on my Ubuntu 16.04. Can you describe your detailed env?

Also, the commit (199911e) is only about for README, suppose it would NOT affect sgx-gdb.

**Comment by Moschn** [comment]
I found the problem: I created a symlink `/usr/local/bin/gdb` -> `/opt/intel/sgxsdk/bin/sgx-gdb`. The `sgx-sdk` script on the master  searches the `gdb` executable first in `/usr/local/bin` and then in `/usr/bin`.  On 199911ebaf60d068e4641331a06e71462ba8d324 it just searches `/usr/bin`. 


(Oh sorry the description was not clear. The commit **after** 199911ebaf60d068e4641331a06e71462ba8d324 broke my debugger. The commit **breaking** it would be 0fb9f47e784261369c52c1b49d1484f34409ecaf. I am testing on the current master but the few changes from then to now should not change the behaviour of `sgx-gdb`.)

**Comment by ZongminGu** [comment]
/usr/local/bin/gdb is the default gdb path in RHEL, so we add it into the search path. Seems we are able to close this bug now.
