### ISSUE TITLE
undefined reference to `sgx_create_enclave'

### ISSUE THREAD

**Issue by soso19932603** [01org/linux-sgx#122]
hi !

I have created intel SGX C project, my project look like this : 
 - Project (root folder)
 - Includes
 - sgx
         - enclave1 (trusted + untrusted + makefile)
         - enclave2 (trusted + untrusted + makefile)
 - Debug
 - Release
 - App
          - App.c 

in app.c file i try to load an enclave using sgx_create_enclave(...). I specified the right include 
   - include "path to sgx_urts.h"
but, when i build, i get this error : undefined reference to `sgx_create_enclave' 

any help !!!

**Comment by ZongminGu** [comment]
If you are using the SGX SDK installer, please use "source [sdk folder]/environment" before build enclave and app.

**Comment by soso19932603** [comment]
hi!! 

I found the solution (it was a c programming problem), i added in the make file for my app.c the following line : 
gcc ............ -L(path to lib64) -l lsgx_urts_sim (case of simulation build)
gcc ........... -L(path to lib64) -lsgx_urts (case of hw build)
for me path to lib64 is /opt/intel/sgxsdk/lib64
