### ISSUE TITLE
stream support in STL

### ISSUE THREAD

**Issue by bl4ck5un** [01org/linux-sgx#126]
Hi,

I'm wondering why `stringstream` is not included in the latest STL? Is there a reason for that or are you guys planning on to support it later? Thanks!

Fan

**Comment by poetchess** [comment]
Hi,
Although `stringstream` just operates on strings, it keeps a set of internal fields inherited from `ios_base`, `ios` and `istream` which are all disabled in tlibcxx. So I think currently we cannot support it.

**Comment by xxu36** [comment]
Hi,
Although `stringstream` just operates on strings, it keeps a set of internal fields inherited from `ios_base`, `ios` and `istream` which are all disabled in tlibcxx. So I think currently we cannot support it.

**Comment by kaimast** [comment]
std::to_string can be used in many cases where you'd want to use stringstream.

Not sure if that is supported by the SDK either though....

**Comment by xxu36** [comment]
`std::to_string` is supported.

**Comment by bl4ck5un** [comment]
Okay. Sounds like you don't have a plan on supporting stream.

**Comment by xxu36** [comment]
yes, it is not in our plan currently.

**Comment by bl4ck5un** [comment]
@xxu36 Thanks. If this changes in the future, could you please post it here?

**Comment by xxu36** [comment]
Sure, thanks
