### ISSUE TITLE
Unable to build the pre-built binaries from source code

### ISSUE THREAD

**Issue by heartever** [01org/linux-sgx#133]
I tried two ways to build the pre-built binaries by myself. I am working on the 1.9 version with gcc-5.4.0 on Ubuntu 16.04.4.
1. Use `make USE_OPT_LIBS=0` to use the non-optimized source code version implementation, as stated in the README.md. Then `make sdk_install_pkg USE_OPT_LIBS=0` succeeds, `make psw_install_pkg USE_OPT_LIBS=0` fails. It still looks for the pre-built binaries in the folder `psw/ae/data/prebuilt`.
2. Build each Architecture Enclave by using the `make` command from the corresponding folder, e.g. the `psw/ae/qe` folder. There turns out to be some compiling errors or link errors.

I am trying to understand how the quoting enclave works. Is the pre-built `libsgx_qe.signed.so` compiled from the provided sources? Is it all right to refer to the implementation in the `qe` folder?

**Comment by lzha101** [comment]
Non-optimized source code version is only used to build SDK. Building Architecture Enclaves(AEs) with non-optimized source code is not supported. All the prebuilt AEs are built with the optimized libraries, inlcuding libsgx_qe.signed.so.

**Comment by hyjiang** [comment]
In addition, Pre-built AEs are signed by Intel specific keys. 
So you cannot fully reproduce the pre-built AEs by yourself, as you don't have the private keys.

If you just want to try/debug the AEs, you may need to signed the AEs by your own keys, then test them on an unlocked system.

**Comment by heartever** [comment]
Is it safe to assume that the prebuilt `libsgx_qe.signed.so` and the source code `psw/ae/qe/` follows the same routine to generate the quote? I'd like to understand how the quote is generated, specifically how the EPID scheme works. Here is a detailed implementation of EPID: [https://software.intel.com/en-us/articles/intel-enhanced-privacy-id-epid-security-technology]. I would also like to know which version of EPID (R2, R3, R4) is used.
@hyjiang I only want to try/debug the AEs. It seems that I cannot build the AEs from the source code.

**Comment by lzha101** [comment]
@heartever  We provide two version of IPP/string/math libraries (precompiled lib version and source code version). `USE_OPT_LIBS=0` means you want to use these libraries of the source code version.  But I don't think you want to debug these optimized libs.  You can build the AEs by yourself to link the precompiled lib version if you don't specify `USE_OPT_LIBS=0`.  We only do not support to build the AEs with the optimized libs of the source code version. 
Just as @hyjiang said, you may be not able to debug the AEs even if you build them out because of the system limitation.

**Comment by heartever** [comment]
Thanks, @lzha101 and @hyjiang. I am trying to gain some understanding of the security of the crypto-algorithms underlies the EPID scheme. While it's difficult to analyze the prebuilt ``libsgx_qe.signed.so``, it will be easier if I can go through the source code instead. My concern is whether the prebuilt ``libsgx_qe.signed.so`` is actually built from the source code in ``psw/ae/qe``. I am interested in the scheme of signing the measurement using the private EPID key.

**Comment by andyzyb** [comment]
Below branch is the exact source to build QE.

https://github.com/01org/linux-sgx/tree/sgx_1.7_ae_signing

**Comment by heartever** [comment]
Thanks @andyzyb
