### ISSUE TITLE
How to use sgx_emmt for enclave memory measurement

### ISSUE THREAD

**Issue by avradip** [01org/linux-sgx#136]
the linux developer [reference](https://01.org/sites/default/files/documentation/intel_sgx_sdk_developer_reference_for_linux_os_pdf.pdf)  page 23-24 provides three steps for using sgx_emmt
1. run sgx-gdb
2. enable sgx_emmt
3. run the app

However, I am not seeing any output for memory usage, am i missing something?
![image](https://user-images.githubusercontent.com/82031/29098041-ffe95fa0-7c51-11e7-82e5-068aba50d277.png)

**Comment by xxu36** [comment]
Hi,
Typically `sgx_destroy_enclave( )` will trigger emmt display.  I'd like to know whether you call this destroy API in your code ?

**Comment by llly** [comment]
It seems that your app didn't call sgx_destroy_encalve(). sgx-gdb will measure the enclave memory usage after calling sgx_destroy_encalve().

**Comment by avradip** [comment]
Thanks a lot. It's now working.
