### ISSUE TITLE
SGX centos support

### ISSUE THREAD

**Issue by light1021** [01org/linux-sgx#144]
Hello everyone：
I installed sgx sdk on centos 7.3 by following steps described in the installation guide， but there are some issues when everything was done.

   1.  I find that aemsd can't start due to libprotobuf.so.9 is missing;
   2.  When trying to build the sample code, there is a link error: "unrecognized relocation (0x2a) in section". 
        I tried to solve this by install gcc 5.3 manually, but it didn't work.
So, What can I do to make SGX works on centos 7.3(1611) ?

Thanks
You

**Comment by andyzyb** [comment]
Are you using the pre-built installer from 01.org?  The one on 01.org is only for Ubuntu 16.04.  To use on CentOS, you need to build from github source code.

**Comment by light1021** [comment]
OK, I will try this.

**Comment by light1021** [comment]
Hi: 
I tried to build from source code but error occurred :
"对‘google::protobuf::internal::kEmptyString[abi:cxx11]’未定义的引用"

**Comment by lzha101** [comment]
I guess it is caused by the incompatibility between the protobuf lib and the GCC version on your machine. You mentioned you installed GCC 5.3 manually. Please try to use the original GCC (not GCC 5.3) to build the code. If you still want to use GCC 5.3, you can try to modify the makefiles to add an additional option '-D_GLIBCXX_USE_CXX11_ABI=0' before building the code.

**Comment by light1021** [comment]
I have tried both，but it didn't work. Can you tell me exactly which version of protobuf do I need to link aemsd ?

**Comment by andyzyb** [comment]
Did you follow all the steps in the README to install required software package?

**Comment by light1021** [comment]
Yes, I installed the required packages before build the code from source.

**Comment by light1021** [comment]
This is my link command: 
`/usr/bin/g++ -Wnon-virtual-dtor -std=c++0x -fstack-protector -O2   -UDEBUG -DNDEBUG -ffunction-sections -fdata-sections -Wall -Wextra -Winit-self -Wpointer-arith -Wreturn-type -Waddress -Wsequence-point -Wformat-security -Wmissing-include-dirs -Wfloat-equal -Wundef -Wshadow -Wcast-align -Wconversion -Wredundant-decls -DITT_ARCH_IA64  -fPIC AECloseSessionRequest.o AEGetQuoteResponse.o AECloseSessionResponse.o AEInitQuoteRequest.o AECreateSessionRequest.o AEInitQuoteResponse.o AECreateSessionResponse.o AEInvokeServiceRequest.o AEExchangeReportRequest.o AEInvokeServiceResponse.o AEExchangeReportResponse.o ProtobufSerializer.o AEGetLaunchTokenRequest.o AEGetPsCapRequest.o AEGetPsCapResponse.o AEGetWhiteListSizeRequest.o AEGetWhiteListSizeResponse.o AEGetWhiteListRequest.o AEGetWhiteListResponse.o AESGXGetExtendedEpidGroupIdRequest.o AESGXGetExtendedEpidGroupIdResponse.o AESGXSwitchExtendedEpidGroupRequest.o AESGXSwitchExtendedEpidGroupResponse.o AEReportAttestationRequest.o AEReportAttestationResponse.o SocketTransporter.o AEGetLaunchTokenResponse.o UnixCommunicationSocket.o NonBlockingUnixCommunicationSocket.o AEGetQuoteRequest.o UnixSocketFactory.o NonBlockingUnixSocketFactory.o  consttime_memequal.o AESMLogicWrapper.o CAESMServer.o main.o Thread.o AESMWorkerThread.o AESMQueueManager.o CSelector.o UnixServerSocket.o ./source/oal/aesm_util.o aesm_config.o aesm_http_msg.o source/pse_op/jhi_proxy.o messages.pb.o sqlite3.o libaesm_service_common.a -pthread -L/root/linux-sgx/build/linux -lurts_internal -L/root/linux-sgx/sdk/tlibcrypto -lsgx_tcrypto -lprotobuf -lrt -lcrypto  -lcurl   -L/root/linux-sgx/common/se_wrapper -lwrapper -lrt -L/root/linux-sgx/external/rdrand/src -lrdrand -L/root/linux-sgx/external/vtune/linux/sdk/src/ittnotify -littnotify   -o aesm_service -ldl
`
/usr/bin/g++ is the default g++ of centos 7.3.

**Comment by light1021** [comment]
Hi andyzyb and lzha101:

Thanks for your help. Maybe some of my previous work have do something wrong to the link dependency of ld. I reset everything, uninstalled gcc5.3 and other version of protobuf. Now it works.
This issue can be closed.

Thanks
you
