### ISSUE TITLE
Linking static libraries on linux? 

### ISSUE THREAD

**Issue by kaimast** [01org/linux-sgx#145]
Hi,

There seems almost now documentation on how to link a static library to an enclave when not using visual studio.

Here is says that 'The user can link with static libraries as long as they do not have any dependencies.': https://software.intel.com/en-us/node/708964
And that is basically all I can find.

I can link a static library successfully against the sgx_tcxx, but when linking it to my enclave I still get a lot of undefined references.

My linking step looks like this right now: 
```
c++  -o enclave.so [CPP_OBJECTS] -L/opt/intel/sgxsdk/lib64 -Wl,--no-undefined -Wl,--as-needed -Wl,--no-undefined -nostdlib -nodefaultlibs -nostartfiles -Wl,--whole-archive -Wl,--start-group -lsgx_trts -Wl,--no-whole-archive
 -Wl,--start-group -lsgx_tstdc -lsgx_tcxx -lsgx_tkey_exchange -lsgx_tcrypto -lsgx_tservice -Wl,--end-group
 -ldocument_sgx -lchipy_sgx  
 -Bstatic -Wl,-Bsymbolic -Wl,--no-undefined -Wl,-pie,-eenclave_entry -Wl,--export-dynamic -Wl,--defsym,
__ImageBase=0 -Wl,--gc-sections -Wl,--version-script=[PROJECT_FOLDER]/Enclave.lds
```

Any help would be appreciated.

document_sgx and chipy_sgx are the two libraries I am trying to link

**Comment by llly** [comment]
Try to put your own library names between OBJECTS and $(App_Link_Flags) .

**Comment by andyzyb** [comment]
What unresolved symbols you've got?  If your static libraries are using other library, please also put it in link command.   

Also suggest to have the static library in "--start-group -lsgx_tstdc -lsgx_tcxx -lsgx_tkey_exchange -lsgx_tcrypto -lsgx_tservice **-ldocument_sgx -lchipy_sgx** -Wl,--end-group"

**Comment by kaimast** [comment]
I found out the problem was setting -fvisibility=hidden when compiling the library.
