### ISSUE TITLE
prebuilt library 

### ISSUE THREAD

**Issue by miraelim** [01org/linux-sgx#152]
When I am trying to execute $ ./download_prebuilt.sh in linux-sgx directory, it fail to download file with error
(ERROR 503 : Service Unavailable
What should I do?

**Comment by lzha101** [comment]
Perhaps you need check your network.  `wget` comand is used to download the prebuilt binaries. You can check if a proxy is required for the command and retry it again.

**Comment by dushyantbehl** [comment]
I'm getting the same error and it seems like download.01.org is down and  (https://download.01.org/intel-sgx/linux-1.9/) is giving the 503 error. Is it possible to get the prebuilt binaries, SDK & PSW from some other source?

**Comment by lzha101** [comment]
Yes, the linkage you provided is unavailable currently (temporary state). But you still can download the prebuilt binaries with the following linkages from web browser: 
https://download.01.org/intel-sgx/linux-1.9/optimized_libs-1.9.100.39124.tar
https://download.01.org/intel-sgx/linux-1.9/prebuilt-ae-1.9.100.39124.tar

And the `download_prebuilt.sh` still works on Linux.

**Comment by miraelim** [comment]
I tried 
wget https://download.01.org/intel-sgx/linux-1.9/optimized_libs-1.9.100.39124.tar and 
wget https://download.01.org/intel-sgx/linux-1.9/prebuilt-ae-1.9.100.39124.tar
but it still has same error.
Also, download_prebuilt.sh still  doesn't work on Linux.

**Comment by dushyantbehl** [comment]
Same here, I tried browser and wget (on linux) both are not woking.

**Comment by yuyuany** [comment]
The server seems to be down. I'm sorry for the inconvenience. The binaries are uploaded to 01.org. You can try to download the binaries from the following links:
https://01.org/sites/default/files/downloads/intelr-software-guard-extensions-linux-os/optimizedlibs-1.9.100.39124.tar
https://01.org/sites/default/files/downloads/intelr-software-guard-extensions-linux-os/prebuilt-ae-1.9.100.39124.tar

**Comment by FedexCain** [comment]
Those links work for me, could you also post links to the documentation?

**Comment by yuyuany** [comment]
Sure. Documentation can be found from:
https://01.org/sites/default/files/downloads/intelr-software-guard-extensions-linux-os/documentation-intel-sgx-linux-1.9-release.zip

**Comment by lzha101** [comment]
The download.01.org server is back now.  You can have a try to download the binaries with the `download_prebuilt.sh`
