### ISSUE TITLE
remote attestation Questation

### ISSUE THREAD

**Issue by light1021** [01org/linux-sgx#156]
Hi: I'd like to do remote attestation in such a scenario:

server get quote and sent to IAS------> get IAS response from IAS---------sent IAS response to client---------->client verify IAS response with IAS public key

Where can I obtain the IAS public key? Thanks

**Comment by rodolfoams** [comment]
Hi. You can find IAS public certificate [here](https://software.intel.com/en-us/sgx/resource-library). It is the last link on the page.

**Comment by light1021** [comment]
Thank you! It's very helpful !
