### ISSUE TITLE
how to build sgx sdk itself under debug mode?

### ISSUE THREAD

**Issue by myvyang** [01org/linux-sgx#180]
I follow the doc, build with `make sdk_install_pkg DEBUG=1`.

but i can only debug enclave code write by me, not the lib like libsgx_tcrypto.a
I want to step into the lib code.

**Comment by lzha101** [comment]
Did you run this command after you run 'make' for the repo code?

**Comment by myvyang** [comment]
@lzha101 my fault, i run this commond in `linux-sgx/sdk` .

I rerun it in linux-sgx and problem solved.

**Comment by myvyang** [comment]
the tcrypto is still not debugable, my version is not 2.0, I'll update and try later.

**Comment by myvyang** [comment]
@lzha101 

2.0 does not contains source code of libipp

is there anyway i can debug the code on 1.X ?
