### ISSUE TITLE
Enable SGX on BIOS that says "Software Controlled" on Linux

### ISSUE THREAD

**Issue by CiraciNicolo** [01org/linux-sgx#183]
Hi,

on the machine which I'm working on, on the BIOS option, the SGX entry has as options only "Disable" or "Software Controller". Reading [this](https://software.intel.com/en-us/articles/properly-detecting-intel-software-guard-extensions-in-your-applications) I have to use `sgx_enable_device` but unfortunately, that function is not available in the Linux SDK. How can I enable SGX on my supported machine?

Motherboard: Asus Z270-A
CPU: i7-7700

**Comment by rodolfoams** [comment]
Hi,

you can use the sgx_cap_enable_device function, which is available in the Linux SDK.
For more information, check the sgx_capable.h header file.

Regards
