### ISSUE TITLE
enclave memory usage

### ISSUE THREAD

**Issue by marcindodo** [01org/linux-sgx#191]
Hi,

I use sgx-gdb and option sgx_emmt. I did everything as described in the developer guide and heap is correct size but stack is always 0 kB. Do you know what a problem could be?

Thanks!

**Comment by xxu36** [comment]
Hi, 
I assume you measured the memory usage on your own enclave? Could you apply the sgx_emmt tool on the SampleEnclave project located in SampleCode directory and check whether that works? On my local environment, that works fine.
If that also works for you, can you share the enclave configuration to me?
Thanks

**Comment by xxu36** [comment]
I've reproduced locally and fixed it. Will update the repo soon.

**Comment by marcindodo** [comment]
Hi,
yes, I use own enclave and for SampleEnclave everything is OK.
If you were able to reproduce the problem, I will wait for the fix. 
Thanks
