### ISSUE TITLE
Undefined reference for static library

### ISSUE THREAD

**Issue by gmatesunny** [01org/linux-sgx#198]
I created an SGX static trusted library using eclipse plugin. It generated as 
/home/roshan/workspace/test_lib/sgx/trustedlib_trusted/libtrusted.sgx.static.lib.a

My static library edl file is this:
```
/* trusted.edl - Top EDL file. */

enclave {
    
    untrusted {
    };

    trusted {
    	    public int ecall_trusted_sample();
    	    public int ecall_inside_encalve();
    };
};

```
and the testlib.cpp

#include "trusted_t.h"

int ecall_inside_encalve()
{
	return 99;
}

now I wanted to use this static libtrusted.sgx.static.lib.a in another SGX project. say project "test"

so in test.edl I wrote [[snippets]
```
enclave {
	from "trusted.edl" import *;
```

and the makefile of trusted and untrusted file [snippets]

```

TESTLIB_DIR := /home/roshan/workspace/test_lib/sgx/trustedlib_trusted
Test_Link_Flags :=  -L$(TESTLIB_DIR) -ltrusted.sgx.static.lib


trusted/test_t.c: $(SGX_EDGER8R) ./trusted/test.edl
	@cd ./trusted && $(SGX_EDGER8R) ../trusted/test.edl --search-path ../trusted --search-path $(SGX_SDK)/include --search-path $(TESTLIB_DIR)/static_trusted
	@echo "GEN  =>  $@"
```

When I try to build, it fails with:

```
trusted/test_t.o: In function `sgx_ecall_inside_encalve':
/home/roshan/workspace/test/sgx/enclave_test/trusted/test_t.c:69: undefined reference to `ecall_inside_encalve'
```

Any help regarding this?

**Comment by zhaohuidu** [comment]
You could have a try to remove test_t.h and test_t.c and rebuild your project. It is likely that the two files are inconsistent to each other

**Comment by gmatesunny** [comment]
Deleted every auto generated file and rebuild. It worked. Thanks :)
