### ISSUE TITLE
aesm_service won't start

### ISSUE THREAD

**Issue by bl4ck5un** [01org/linux-sgx#20]
`aesmd_service` can not be started. 

```
journalctl -u aesmd.service
Sep 25 15:41:12  aesm_service[2601]: SGX Service unavailable
Sep 25 15:41:12  aesm_service[2601]: Fail to start service.
```

**Comment by zhaohuidu** [comment]
What is the OS version do you used? 
How about SGX driver status (You could have a try to run "lsmod |gre p isgx")?
And aesm_service is dependent on some pre-installed package. Are all those packages installed in your machine? such as 
sudo apt-get install libcurl4-openssl-dev protobuf-compiler protobuf-c-compiler libprotobuf-dev libprotobuf-c0-dev

**Comment by andyzyb** [comment]
Please kindly provide enough details for reproducing the issue, like OS version, hardware being used (if SGX enabled in BIOS), how you build/install the software, etc.

**Comment by bl4ck5un** [comment]
Problem solved. It turned out `isgx` was not properly loaded.

**Comment by donporter** [comment]
I am having this issue on Ubuntu 16.04, x86_64.  SGX seems like it is enabled in the BIOS, and the driver is loaded properly:

[391663.544364] isgx: Intel SGX Driver v0.10
[391663.544425] isgx: EPC memory range 0xd0200000-0xd5f80000

Nov 10 23:44:58  aesm_service[16558]: SGX Service unavailable
Nov 10 23:44:58  aesm_service[16558]: Fail to start service.
Nov 10 23:44:58  systemd[1]: aesmd.service: Main process exited, code=exited, status=1/FAILURE
Nov 10 23:44:58  systemd[1]: aesmd.service: Unit entered failed state.
Nov 10 23:44:58  systemd[1]: aesmd.service: Failed with result 'exit-code'.

Any tips?

**Comment by donporter** [comment]
Looks like the latest code doesn't have this problem. I was trying to roll back to the 1.6 tag.
