### ISSUE TITLE
Compilation issue following the README

### ISSUE THREAD

**Issue by carlosaguilarmelchor** [01org/linux-sgx#25]
Hi,
thank you for this very nice project !

I have an Ubuntu 14.04 64-bits in a vmware virtual machine. My CPU is `Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz` and I am trying to use the project only for simulation. I follow the README procedure for installation with the latest master commit and after running:

`make sdk_install_pkg`

I get

`Generated sdk installer: ./linux/installer/bin/sgx_linux_x86_sdk_1.6.100.34922.bin`

This seems strange to me as I have a 64 bit system and I would expect getting the x64 installer:

```
$ uname -a
Linux zerosix-linux 3.13.0-68-generic #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Then I run the installer and when I try to compile the sample code in SampleCode/LocalAttestation I get

`make: *** Pas de règle pour fabriquer la cible « /XXX/linux/installer/bin/sgxsdk/bin/x64/sgx_edger8r », nécessaire pour « LocalAttestationCode/LocalAttestationCode_t.c ». Arrêt.`

Which means "No rule to make tarkget ... /x64/sgx_edger8r". If I go to the sgxsdk/bin directory I see an x86 directory but no x64 directory which probably means that everything starts being wrong when I get the x86 installer instead of the x64 ... 

Thanks in advance for any help,

best,

Carlos

**Comment by zhaohuidu** [comment]
What is the version of you "make"? (try run "make -v" in your machine).
And you could also have a try to create a Makefile with
all:
         file -L $(SHELL)
(where those space replaced by one TAB)
and run make 
Would you please also post output of the make?
Does it contains 'x86-64' or 'x86_64'

**Comment by zhaohuidu** [comment]
there's a TAB before command 'file -L $(SHELL)' in the makefile

**Comment by carlosaguilarmelchor** [comment]
GNU Make 3.81
I did the makefile (with the TAB ;) ) and I get 

```
file -L /bin/sh
/bin/sh: ELF 64-bit LSB  shared object, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=0f7ff287cf26eba9a6643b1226089eea57cb7e44, stripped
```

Thx for your rapid reply

**Comment by yuyuany** [comment]
Could you change your directory to sgxsdk/bin/x86, and run the following commands:
$ readelf -h sgx_sign |grep Class
$ readelf -h libsgx_urts_sim.so |grep Class

**Comment by carlosaguilarmelchor** [comment]
For the both commands I get `Class: ELF64`. The second command I ran it in the sgxsdk/libs directory as there was no libsgx_urts_sim.so file in sgxsdk/bin.

**Comment by yuyuany** [comment]
Looks weird. Installer detects the architecture just by the command 
    readelf -h $BUILD_DIR/sgx_sign | awk '/Class:/{print $2}'
If the class is ELF64, it should generate x64 installer package. You can find the code in $(sgx)/linux/installer/bin/build-installpkg.sh.  Try './build-installpkg.sh sdk' to see if the problem still exists.

**Comment by carlosaguilarmelchor** [comment]
I get 
`Generated sdk installer: ./sgx_linux_x86_sdk_1.6.100.34922.bin`

**Comment by carlosaguilarmelchor** [comment]
Got it. The installer looks for the string "Class:" but with localized messages "Class" is translated on each non-english speaking country to something else. Mine is "Classe:" I translated it for you and thus hide the bug. 

Maybe an alternative way to test the architecture will support better localization issues.

**Comment by carlosaguilarmelchor** [comment]
Unfortunately this problem probably appears elsewhere as now I get the x64 installer but the final bug ("No rule to make tarkget ... /x64/sgx_edger8r") remains when trying to compiel SampleCode examples ...

**Comment by carlosaguilarmelchor** [comment]
Changing "Class" by the appropriated localized work in linux/installer/common/sdk/createTarball.sh and in linux/installer/bin/build_installpkg.sh solves the issue for me.

Maybe having a non-localization dependent identification of the architecture would be better but for me the issues becomes fixable. 

Thank you for your reactivity.

**Comment by Aaditi3981** [comment]
Hey @carlosaguilarmelchor 
May I know what 'Changing "Class" by the appropriated localized word'  mean?

**Comment by rodolfoams** [comment]
Hi, @Aaditi3981
I believe @carlosaguilarmelchor was referring to a problem that was solved on this commit https://github.com/01org/linux-sgx/commit/cdf56372ec8628c797dc566f9011a201b06b54b9

**Comment by carlosaguilarmelchor** [comment]
Indeed, thank you !
