### ISSUE TITLE
Page permission setup

### ISSUE THREAD

**Issue by jaebaek** [01org/linux-sgx#27]
Hi, I want to report a page permission setting error.
(If there is my mistake, please let me know it)

For my research work, I needed RWX pages.
I tried two ways:
1. add extra RWX pages like heap pages --> I needed to modify the sign tool (i.e., sdk/sign_tool/SignTool/manage_metadata.cpp)
2. add an extra RWX section in the enclave program.

The first way had a problem, so I report it here.

I confirm that the sdk and driver try to setup RWX pages correctly, but it seems that hardware does not set it up as RWX.
Writing shell code to a RWX page works fine, but executing it causes a fault.

I briefly explained this error in [a git repo](https://github.com/jaebaek/SGX-PAGE-ALLOCATION-ERROR).

Could you please explain what is problem?

**Comment by yuyuany** [comment]
We have an assumption that all the pages added by layout table have no X attribute. You can go to psw/urts/loader.cpp and comment out line 764-770, and have a try again.

**Comment by andyzyb** [comment]
No feedback for around a month,  suppose the issue is gone or resolved.
