### ISSUE TITLE
Do you plan support for WSL (Ubuntu "Bash" in Windows 10)?

### ISSUE THREAD

**Issue by GitHubKilla** [01org/linux-sgx#29]
Developing in the recent Windows 10 Ubuntu subsystem (WSL) has several advantages over MS/Visual Studio for me.  The Linux SDK compiles and installs just fine. However, when I try to run an app, I get an error msg like this one:

~/linux-sgx/SampleCode/SampleEnclave$ ./app 
./app: error while loading shared libraries: libsgx_urts_sim.so: cannot enable executable stack as shared object requires: Invalid argument

It his fixable?

**Comment by andyzyb** [comment]
This is an interesting request.  I can reproduce the same issue on WSL.   

Strace shows the issue might be coming from mprotect syscall (with different parameters) is not fully supported by WSL(see below output).   Will look into if there is any possible solution to work around this.

---------------------------------------------------------------------------------------------------------
mmap(NULL, 2279336, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f5b8e5d0000
mprotect(0x7f5b8e5f7000, 2093056, PROT_NONE) = 0
mmap(0x7f5b8e7f6000, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x26000) = 0x7f5b8e7f6000
mmap(0x7f5b8e7f9000, 14248, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f5b8e7f9000
**mprotect(0x7fffef339000, 4096, PROT_READ|PROT_WRITE|PROT_EXEC|PROT_GROWSDOWN) = -1 EINVAL (Invalid argument)**
close(3)                                = 0
writev(2, [{"./app", 5}, {": ", 2}, {"error while loading shared libra"..., 36}, {": ", 2}, {"libsgx_urts_sim.so", 18}, {": ", 2}, {"cannot enable executable stack a"..., 56}, {": ", 2}, {"Invalid argument", 16}, {"\n", 1}], 10./app: error while loading shared libraries: libsgx_urts_sim.so: cannot enable executable stack as shared object requires: Invalid argument
) = 140
exit_group(127)                         = ?
------------------------------------------------------------------------------------------------------

**Comment by andyzyb** [comment]
You can try below workaround to remove executable stack for libsgx_urts_sim.so.  

Please install execstack,  then run the command like below.

$/usr/sbin/execstack -c $(SGXSDK)/sdk_libs/libsgx_urts_sim.so

Then run the sample code.

**Comment by GitHubKilla** [comment]
Nice, this works! Thanks a lot!
