### ISSUE TITLE
You forgot to put "./build-installpkg.sh sdk" in the readme

### ISSUE THREAD

**Issue by hmofrad** [01org/linux-sgx#35]
Hey guys, I'm a newbie trying to install your sdk. I noticed that in "install intel sgx sdk" section of the readme the command to generate the sdk package is missing. I think, it's good to add "$ ./build-installpkg.sh sdk" and organize this section of the readme as follows to eliminate any potential mistake.

$ cd linux/installer/bin
$ ./build-installpkg.sh sdk
$ ./sgx_linux_x64_sdk_${version}.bin

**Comment by zhaohuidu** [comment]
As the readme, you could use
make sdk_install_pkg
to generate the sdk installer package

**Comment by hmofrad** [comment]
I didn't use this command to build the project. Anyhow, thanks for your prompt response.
