### ISSUE TITLE
sgx-gdb throws OSError

### ISSUE THREAD

**Issue by bl4ck5un** [01org/linux-sgx#39]
```
Traceback (most recent call last):
  File "<string>", line 249, in on_stop
  File "<string>", line 292, in build
  File "<string>", line 342, in update_term_width
OSError: [Errno 25] Inappropriate ioctl for device
```

gdb version: GNU gdb (GDB) 7.12

**Comment by andyzyb** [comment]
SGX debugger is broken with latest gdb (gdb 7.12 is likely included),  we are still doing more investigation on what was changed in latest GDB implementation.

**Comment by ZongminGu** [comment]
Please use gdb 7.9.1 before we fix the gdb 1.12 issue.

**Comment by adombeck** [comment]
Is 7.9.1 still the latest supported gdb version?

**Comment by ZongminGu** [comment]
Will support 7.9.1 later version soon.

**Comment by ZongminGu** [comment]
SGX is able to support gdb 7.12 now.

**Comment by andyzyb** [comment]
@bl4ck5un would you please check if the fix works, then close the issue?

**Comment by bl4ck5un** [comment]
@andyzyb Will do. You guys are really doing a great job!
