### ISSUE TITLE
sgx_enable_device

### ISSUE THREAD

**Issue by jbdatko** [01org/linux-sgx#51]
What is the method to enable SGX, when SGX is software controlled, on a linux platform. I have been asking on the Intel [forums](https://software.intel.com/en-us/forums/intel-software-guard-extensions-intel-sgx/topic/703574) and they told me I need to call `sgx_enable_device`. But from [this](https://software.intel.com/en-us/articles/properly-detecting-intel-software-guard-extensions-in-your-applications) document, there isn't a document method to do this from linux.

Can this be done from linux or do I need to do this from a windows VM running on the host?

**Comment by andyzyb** [comment]
This API is not provided in Linux SDK.  You can go directly into the BIOS and turn SGX option to enabled.

**Comment by jbdatko** [comment]
Unfortunately that's the problem. The Bios (Intel Bios) *removed* the
option from the BIOS. So, according to that Intel thread referenced the
only way to enable it is through that API.

Is there any other work around? I could install an old Bios just to enable
it and then reflash the BIOS but this sounds like the definition of an ugly
hack.

**Comment by yuyuany** [comment]
Which version of Intel BIOS are you using? We didn't find any BIOS remove the option.

**Comment by jbdatko** [comment]
S1200SP0
Intel Xeon CPU E3-1270 v5
IFWI Version: S1200SP.BR.64.0008.091420161502
BIOS Version: S1200SP.86B.01.03.0023.091420160802

Under `Processor Configuration` I only see the following options:
Hyber-threading
active processor cores
execute disable bit
intel virt tech
intel txt
intel vt for directed io
enhanced error containment mode
mlc streamer
mlc spatial prefetcher

**Comment by yuyuany** [comment]
Intel SGX is only officially supported on Skylake and KabyLake CPU. As for Intel Xeon CPU E3, there's no official release BIOS to support Intel SGX feature. 
I don't think the call to sgx_enable_device can solve the problem. The API also needs BIOS support. If the SGX feature is not supported by BIOS, the API can do nothing.

**Comment by andyzyb** [comment]
For E3 server, please contact the vendor who provided the system if SGX is supported or which BIOS version enables the SGX.

**Comment by jbdatko** [comment]
The vendor of the motherboard is Intel as is the BIOS. I realize Intel is a big company but I've been having a hard time finding whom is the right contact, I've tried this repo, Intel Support, Intel Forums. If you have any insight, I'd be happy to have it.

Secondly, what does the BIOS technically do with regards to SGX? Can enabling SGX for the platform be done via UEFI shell?

**Comment by andyzyb** [comment]
I will check with internal team to see if there is any suggestion to share.

**Comment by hyjiang** [comment]
For E3 server, you can download the latest Firmware from Intel download center.
https://downloadcenter.intel.com/download/26796/Intel-Server-Board-S1200SPO-S1200SPOR-Firmware-Update-Package-for-EFI-with-Intel-Software-Guard-Extensions-Support?v=t

**Comment by jmechalas** [comment]
The software enable for Linux is now supported in the master branch via sgx_cap_enable_device from libsgx_capable. This does require root (or at least write access to /sys/firmware/efi).

**Comment by jbdatko** [comment]
Thanks y'all. I'll be trying this next week and I'll post an update!

**Comment by jmechalas** [comment]
You might find some of the information in [this article on Intel SGX feature detection](https://software.intel.com/en-us/articles/properly-detecting-intel-software-guard-extensions-in-your-applications) helpful (it was recently updated to include Linux content).

**Comment by jbdatko** [comment]
I update the firmware, enabled SGX, and it's now available in OS. Thank you! I'm closing this issue.
