### ISSUE TITLE
Build issues while doing a make in Ubuntu 14.04

### ISSUE THREAD

**Issue by nikileshsa** [01org/linux-sgx#53]
I am getting a bunch of compilation errors while doing a make in Ubuntu 14.04. 

Attaching the output of Make here. 

Is there any specific arguments I should supply while doing a make? 

I have been trying to follow the instructions in the README file.

[log.txt](https://github.com/01org/linux-sgx/files/634830/log.txt)

**Comment by ZongminGu** [comment]
Can you please point me line number of the error in the log file? The log looks good.

**Comment by llly** [comment]
It seems protoc doesn't work. Try "sudo apt-get install  protobuf-compiler protobuf-c-compiler libprotobuf-dev libprotobuf-c0-dev".

**Comment by nikileshsa** [comment]
@ZongminGu @llly thanks! I was able to get it resolved by installing protoc.
