### ISSUE TITLE
Wrong function name used in Developer Reference

### ISSUE THREAD

**Issue by adombeck** [01org/linux-sgx#54]
In the SDK Developer Reference v1.6 the function name `sgx_get_mac_add_text_len` is used in the description of `sgx_unseal_data` on pages 153 and 154. 
On page 159 the function name `sgx_get_add_mac_text_len` is used.
But in the source code, the function is actually named `sgx_get_add_mac_txt_len`.

**Comment by yuyuany** [comment]
Thank you for reporting the bug. It will be fixed in the next release.

**Comment by lzha101** [comment]
This bug has fixed in the [Developer Reference](https://download.01.org/intel-sgx/linux-1.8/docs/Intel_SGX_SDK_Developer_Reference_Linux_1.8_Open_Source.pdf) of the latest release.  @adombeck, if no problem, can we close this issue?

**Comment by adombeck** [comment]
> @adombeck, if no problem, can we close this issue?
Sure.
