### ISSUE TITLE
How to write a multi-thread program in the enclave? 

### ISSUE THREAD

**Issue by sjtugjy** [01org/linux-sgx#56]
It seems that current SDK does not support pthread.

**Comment by andyzyb** [comment]
Please read sgx developer reference for multi-threaded application
(https://download.01.org/intel-sgx/linux-1.7/docs/Intel_SGX_SDK_Developer_Reference_Linux_1.7_Open_Source.pdf). 

Basically the thread number is statically defined in Enclave configure file, and you cannot dynamically create thread like pthread_create with current SDK.  You can use sgx_mutex for thread synchronization.

**Comment by sjtugjy** [comment]
Thanks.
