### ISSUE TITLE
IAS access 405 error 

### ISSUE THREAD

**Issue by svartkanin** [01org/linux-sgx#59]
Since the code samples do not provide any IAS connection, I was trying to access it via Curl. Unfortunately I receive a 405 method not allowed error with is not even documented in the REST API documentation https://software.intel.com/sites/default/files/managed/3d/c8/IAS_1_0_API_spec_1_1_Final.pdf 

Here is the code part that tries to perform the quote verification:

string WebService::createJSONforIAS(uint8_t *quote, uint8_t *pseManifest, uint8_t *nonce) {
 	  Json::Value request;   
	    string quoteStr = ByteArrayToString(quote, 1116);
	    quoteStr = base64encode(quoteStr);
            request["isvEnclaveQuote"] = quoteStr;
	Json::FastWriter fastWriter;
	std::string output = fastWriter.write(request);
	return output;
}

void WebService::sendToIAS(string str) {
	CURL *curl;
	CURLcode res = CURLE_OK;
	curl = curl_easy_init();
	if (curl) {
		curl_easy_setopt(curl, CURLOPT_URL, "https://test-as.sgx.trustedservices.intel.com:443/attestation/sgx/v1/report");
		curl_easy_setopt(curl, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1_2);
		curl_easy_setopt(curl, CURLOPT_VERBOSE, 1L);
		curl_easy_setopt(curl, CURLOPT_SSLCERT, "/home/kyoto/SICS_MASTERTHESIS/Development/src/WebService/client.pem");
		curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0);
		struct curl_slist *headers = NULL;
		headers = curl_slist_append(headers, "Accept: application/json");
		headers = curl_slist_append(headers, "Content-Type: application/json");
		headers = curl_slist_append(headers, "charsets: utf-8");
		res = curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);
		cout << str << endl;
		curl_easy_setopt(curl, CURLOPT_POSTFIELDS, str);
		curl_easy_setopt(curl, CURLOPT_POSTFIELDSIZE, str.size());
		res = curl_easy_perform(curl);
		if (res != CURLE_OK)
			fprintf(stderr, "curl_easy_perform() failed: %s\n", curl_easy_strerror(res));
		curl_easy_cleanup(curl);
	}
}

and here the output of curl:

`*   Trying 208.39.114.225...`
`* Connected to test-as.sgx.trustedservices.intel.com (208.39.114.225) port 443 (#0)`
`* ALPN, offering http/1.1`
`* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH`
`* successfully set certificate verify locations:`
`*   CAfile: /etc/ssl/certs/ca-certificates.crt`
`  CApath: /etc/ssl/certs`
`* NPN, negotiated HTTP1.1`
`* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256`
`* ALPN, server did not agree to a protocol`
`* Server certificate:`
`* 	 subject: C=US; ST=CA; L=Santa Clara; O=Intel Corporation; CN=test-as.sgx.trustedservices.intel.com`
`* 	 start date: Sep 14 17:24:30 2016 GMT`
`* 	 expire date: Sep  4 17:24:30 2018 GMT`
`* 	 subjectAltName: test-as.sgx.trustedservices.intel.com matched`
`* 	 issuer: C=US; ST=CA; L=Santa Clara; O=Intel Corporation; CN=Intel External Issuing CA 6A`
`* 	 SSL certificate verify ok.`
`> POST /attestation/sgx/v1/report HTTP/1.1`
`Host: test-as.sgx.trustedservices.intel.com`
`Accept: application/json`
`Content-Type: application/json`
`charsets: utf-8`
`Content-Length: 2999`
`Expect: 100-continue`

`< HTTP/1.1 100 Continue`
`* We are completely uploaded and fine`
`< HTTP/1.1 405 Method Not Allowed`
`< Request-ID: 61bc4e8be2c646ebbcb97ad52d005e18`
`< Date: Thu, 12 Jan 2017 14:54:30 GMT`
`< Connection: keep-alive`
`< Transfer-Encoding: chunked`
`

Any idea why this is failing?

**Comment by andyzyb** [comment]
I don't think you can access IAS directly.  Please check https://software.intel.com/en-us/sgx-sdk-support, and ask the question in the forum to get more support.

**Comment by rodolfoams** [comment]
Hi, svartkanin.
Here is a fully functional code using IAS:

struct attestation_evidence_payload_t
{
    std::string isv_enclave_quote;
};

template<typename X>
inline void serialize( jsoncpp::Stream<X>& stream, attestation_evidence_payload_t& aep )
{
    fields( aep, stream, "isvEnclaveQuote", aep.isv_enclave_quote );
}

struct ias_response_header_t
{
    int response_status;
    int content_length; 
    std::string request_id;
};

struct ias_response_container_t
{
    char *p_response;
    size_t size;
};

struct attestation_verification_report_t
{
    std::string report_id;
    std::string isv_enclave_quote_status;
    std::string timestamp;
};

template<typename X>
inline void serialize( jsoncpp::Stream<X>& stream, attestation_verification_report_t& avr )
{
    fields( avr, stream, "isvEnclaveQuoteStatus", avr.isv_enclave_quote_status, "id", avr.report_id, "timestamp", avr.timestamp );
}

size_t ias_response_header_parser( void *ptr, size_t size,
                       size_t nmemb, void *userdata )
{
    int parsed_fields = 0, response_status, content_length, ret = size * nmemb;

    char *x = ( char * ) calloc( size + 1, nmemb );
    assert( x );
    memcpy( x, ptr, size * nmemb );
    parsed_fields = sscanf( x, "HTTP/1.1 %d", &response_status );
    if ( parsed_fields == 1 )
    {
        ( ( ias_response_header_t * ) userdata )->response_status = response_status;
        return ret;
    }

    parsed_fields = sscanf( x, "content-length: %d", &content_length );
    if ( parsed_fields == 1 )
    {
        ( ( ias_response_header_t * ) userdata )->content_length = content_length;
        return ret;
    }

    char *p_request_id = ( char * ) calloc( 1, REQUEST_ID_MAX_LEN );
    parsed_fields = sscanf( x, "request-id: %s", p_request_id );
    if ( parsed_fields == 1 )
    {
        std::string request_id_str( p_request_id );
        ( ( ias_response_header_t * ) userdata )->request_id = request_id_str;
        return ret;
    }
    return ret;
}

size_t ias_reponse_body_handler( void *ptr, size_t size,
                       size_t nmemb, void *userdata )
{
    size_t realsize = size * nmemb;
    ias_response_container_t *ias_response_container = ( ias_response_container_t * ) userdata;
    ias_response_container->p_response = ( char * ) realloc( ias_response_container->p_response, ias_response_container->size + realsize + 1 );
    if ( ias_response_container->p_response == NULL )
    {
        fprintf( OUTPUT, "\n[SERVER] Unable to allocate extra memory\n" );
        return 0;
    }

    memcpy( &( ias_response_container->p_response[ ias_response_container->size ] ), ptr, realsize );
    ias_response_container->size += realsize;
    ias_response_container->p_response[ ias_response_container->size ] = 0;

    return realsize;
}

bool verify_quote_with_IAS( char *p_encoded_quote, attestation_verification_report_t *p_avr )
{
    CURL *curl;
    CURLcode res;

    curl_global_init( CURL_GLOBAL_DEFAULT );

    curl = curl_easy_init( );
    if ( !curl ) return false;   

    static const char *p_cert_file = CERT_PATH;
    std::string isv_enclave_quote( p_encoded_quote );
    attestation_evidence_payload_t aep{ isv_enclave_quote };
    const auto aep_json = jsoncpp::to_string( aep );

    struct curl_slist *headers = NULL;
    headers = curl_slist_append(headers, "Content-Type: application/json");

    curl_easy_setopt( curl, CURLOPT_URL, "https://test-as.sgx.trustedservices.intel.com:443/attestation/sgx/v1/report" );
    curl_easy_setopt( curl, CURLOPT_VERBOSE, 1L );
    curl_easy_setopt( curl, CURLOPT_SSLCERTTYPE, "PEM" );
    curl_easy_setopt( curl, CURLOPT_SSLCERT, p_cert_file );
    curl_easy_setopt( curl, CURLOPT_USE_SSL, CURLUSESSL_ALL );
    curl_easy_setopt( curl, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1_2 );
    curl_easy_setopt( curl, CURLOPT_NOPROGRESS, 1L);
    curl_easy_setopt( curl, CURLOPT_HTTPHEADER, headers );
    curl_easy_setopt( curl, CURLOPT_POSTFIELDS, aep_json.c_str( ) );

    ias_response_header_t response_header;

    ias_response_container_t ias_response_container;
    ias_response_container.p_response = ( char * ) malloc( 1 );
    ias_response_container.size = 0;

    curl_easy_setopt( curl, CURLOPT_HEADERFUNCTION, ias_response_header_parser );
    curl_easy_setopt( curl, CURLOPT_HEADERDATA, &response_header );
    curl_easy_setopt( curl, CURLOPT_WRITEFUNCTION, ias_reponse_body_handler );
    curl_easy_setopt( curl, CURLOPT_WRITEDATA, &ias_response_container );

    res = curl_easy_perform( curl );
    if ( res != CURLE_OK )
    {
        fprintf( stderr, "curl_easy_perform() failed: %s\n",
                curl_easy_strerror( res ) );
                return false;
    }
    fprintf( stdout, "\nResponse from IAS:\n%s\n", ias_response_container.p_response );

    attestation_verification_report_t avr;
    std::string avr_str( ias_response_container.p_response );
    jsoncpp::parse( avr, avr_str );

    if ( avr.isv_enclave_quote_status.compare( "OK" ) != 0 )
    {
        fprintf( stdout, "\nQuote is not valid!\n" );
        return false;
    }

    fprintf( stdout, "\nSuccessfully verified Quote with IAS\n" );

    return true;
}

**Comment by svartkanin** [comment]
Great thanks a lot for the example it worked perfectly!!

**Comment by andyzyb** [comment]
Looks this can be closed.

**Comment by gmatesunny** [comment]
I tried to use @rodolfoams code,  but it is not working. Do you have working example ?

**Comment by svartkanin** [comment]
Here is a full working example
[https://github.com/svartkanin/linux-sgx-remoteattestation](url)
