### ISSUE TITLE
Support for protected file system

### ISSUE THREAD

**Issue by anithag** [01org/linux-sgx#61]
I am looking for support for protected file system API. Windows version has basic support. Link below:

[Support for Protected File System a basic subset of the regular ‘C’ file API for Intel 
SGX enclaves that provides files with both confidentiality and integrity protection](https://software.intel.com/sites/default/files/managed/d1/0a/Intel-SGX-SDK-Release-Notes-for-Windows-OS.pdf)

Does Linux version already support this feature? If not, is this planned to be implemented real soon?
Thanks!
Anitha

**Comment by andyzyb** [comment]
It is in the progressing of porting to Linux, and probably will be available soon.

**Comment by anithag** [comment]
Thanks. I am waiting for the feature. Any expected timeline?

**Comment by andyzyb** [comment]
No exact timeline so far.  May come in next a few months.

**Comment by llly** [comment]
protected file system is available now, since 1.9 release.
