### ISSUE TITLE
Use of possibly uninitialized int as function pointer

### ISSUE THREAD

**Issue by adombeck** [01org/linux-sgx#74]
In [`do_ctors_aux()`](https://github.com/01org/linux-sgx/blob/master/sdk/trts/linux/global_init.c#L57) the  `uintptr_t init_array_addr` is used as the base for a function pointer, which is then called in [line 77](https://github.com/01org/linux-sgx/blob/master/sdk/trts/linux/global_init.c#L77). The `init_array_addr` might still be uninitialized at that point, the [`elf_get_init_array()`](https://github.com/01org/linux-sgx/blob/master/sdk/trts/linux/elf_parser.c#L377) does not assign a value to it in each case.

**Comment by llly** [comment]
We will fix this bug in the coming major release.

**Comment by lzha101** [comment]
The bug is fixed in the latest 1.8 Release. Close this issue.
