### ISSUE TITLE
Support for Ubuntu LTS 16.04

### ISSUE THREAD

**Issue by mitar** [01org/linux-sgx#77]
It would be great if there could be official support for Ubuntu LTS 16.04. It seems it works, but official support would be easier to run it in production.

**Comment by andyzyb** [comment]
The Ubuntu 16.04 support is in the plan and will come out soon.

**Comment by mitar** [comment]
I can confirm that intel-sgx-driver works on Ubuntu LTS 16.04.

**Comment by llly** [comment]
Ubuntu 16.04 LTS is official supported now.
