### ISSUE TITLE
sgx_init_quote is returning strange target_info

### ISSUE THREAD

**Issue by mitar** [01org/linux-sgx#82]
When I run `sgx_init_quote` and inspect resulting `target_info` contents, I get strange output, in base64:

```
7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u4BAAAAAAAAAAMAAAAAAAAA4Ol6AwAAAAAAAAAAAAAAAIDSNAv+fwAAXdgmikx/AADw1TQL/n8AAJbLMgEAAAAAnZoCAAAAAADPHKgsAAAAANDVNAv+fwAAMDe1AAAAAAAAAAAAAAAAAMhnfgMAAAAAANM0C/5/AAAs88UAAAAAAODSNAv+fwAAAgAAAAAAAAAwMoYDAAAAAM6PwbsnAAAA4Il6AwAAAABY1zQL/n8AAFjXNAv+fwAA6Gd+AwAAAABBQgB2yiEAAAAAAAAAAAAAAAAAAAAAAAC7i9cAAAAAAAibhgMAAAAA2Gd+AwAAAACQaH4DAAAAAOCJegMAAAAAyGd+AwAAAADgiXoDAAAAADCHfgMAAAAAWNc0C/5/AADgiXoDAAAAADCHfgMAAAAAQNY0C/5/AABY1zQL/n8AAMhnfgMAAAAAk4nLpLYCAAAYzXsDAAAAAOCJegMAAAAAEM17AwAAAACTicuktgIAAODTNAv+fwAAfW/HAAAAAADw0zQL/n8AACDWNAv+fwAAsNQ0C/5/AAAg1jQL/n8AAAEAAAAAAAAAINc0C/5/AACw1DQL/n8AAJDUNAv+fwAAUNQ0C/5/AAAw/NoAAAAAAGDUNAv+fwAAMPzaAAAAAAA=
```

When I provide this target info to `sgx_create_report` it fails with `SGX_ERROR_INVALID_PARAMETER`. Because reserved bytes are non-zero.

**Comment by mitar** [comment]
Oh, I found the issue. Buffers I was passing to `sgx_init_quote` were not zeroed out initially. It seems `sgx_init_quote` only sets parts of a buffer and does not set the rest (reserved bytes) to zero. I think SDK should do that.

A workaround is that for now I set everything to zero before calling `sgx_init_quote`.

**Comment by llly** [comment]
A new major release is updated. You can test it.

**Comment by mitar** [comment]
I can confirm that this is not a problem anymore with 1.8.
