### ISSUE TITLE
sgx_get_quote_size takes sig_rl and not sig_rl_size

### ISSUE THREAD

**Issue by mitar** [01org/linux-sgx#84]
This is so strange. Shouldn't `sgx_get_quote_size` take in the size of the revocation list, in bytes? And not the list itself? Or at least both the list and the size?

**Comment by llly** [comment]
sgx_get_quote_size calculates quote_size with sig_rl contents in case of multiple version of sig_rl supported.

**Comment by andyzyb** [comment]
It seems the size of buffer is needed for sgx_get_quote_size.  We will review it carefully. 

sgx_get_quote will send the sig_rl to another process, so the size of memory is needed to across process boundary.

**Comment by llly** [comment]
New interface sgx_calc_quote_size is added. sgx_get_quote is marked as deprecated.
