### ISSUE TITLE
make SDK installer non-interactive

### ISSUE THREAD

**Issue by bl4ck5un** [01org/linux-sgx#90]
Hi, guys,

It would be really handy for scripting if the SDK installer doesn't ask questions (Do you want to install in the current directory? [yes/no] ). I'd suggest using arguments to do this (e.g. `--prefix`), which seem to be more standard...

Best,
Fan

**Comment by llly** [comment]
It's OK to use argument for install directory. However we really need you to accept the license.

**Comment by mitar** [comment]
But this is hard to package the SDK into Docker image. Many other packages allow you to pass an argument to accept it. There is really no difference between interactively accepting it or accepting it through a command line. `--accept-license` clearly signals your intent.

Anyway, workaround I am using for now is `yes yes | linux/installer/bin/sgx_linux_x64_sdk_*.bin`.

**Comment by llly** [comment]
Will update sdk installer to add argument in new major release.

**Comment by llly** [comment]
--prefix argument is supported in 1.9 release.
